{
 "title": "Logs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "plugin",
    "label": "Plugin",
    "query": "brewertender,stretchy,ruscue,weathery,rustea"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server",
   "type": "logs",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"rusty-server\"}"
    }
   ]
  },
  {
   "title": "Plugins runner",
   "type": "logs",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/rusty-controller/run-all.log\"}"
    }
   ]
  },
  { "title": "Plugins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$plugin",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "repeat": "plugin",
   "targets": [
    {
     "expr": "{filename=\"/var/log/rusty-controller/plugins/$plugin.log\"} |= ``"
    }
   ]
  },
  { "title": "Plugins cron logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "$plugin",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "repeat": "plugin",
   "targets": [
    {
     "expr": "{filename=\"/var/log/rusty-controller/plugins/cron/$plugin.log\"} |= ``"
    }
   ]
  }
 ]
}