{
 "title": "Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "task",
    "label": "Task",
    "query": "controller_update,controllers_list,effects_update"
   }
  ]
 },
 "panels": [
  { "title": "Connected Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "connected_devices" }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "controllers",
     "endTimePath": "endTime",
     "queryText": "query {\n      controllers {\n        address\n        connectionType\n        batteryLevel\n        currentLedEffect\n      }\n}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "[$task] Scheduled duration",
   "type": "timeseries",
   "description": "Time it waited to start running",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "repeat": "task",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scheduled_duration_sum{task=\"$task\"}[2m]) / rate(scheduled_duration_count{task=\"$task\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$task] Poll duration",
   "type": "timeseries",
   "description": "Time it spent running",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "repeat": "task",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(poll_duration_sum{task=\"$task\"}[2m]) / rate(poll_duration_count{task=\"$task\"}[2m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$task] Idle duration",
   "type": "timeseries",
   "description": "Time it slept (waiting for the interval tick)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "repeat": "task",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(idle_duration_sum{task=\"$task\"}[2m]) / rate(idle_duration_count{task=\"$task\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}